// <auto-generated />
using System;
using BankApp.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankApp.Services.Migrations
{
    [DbContext(typeof(BankDBContext))]
    [Migration("20210327093120_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankApp.Models.AccountHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankModelId");

                    b.ToTable("AccountHolders");
                });

            modelBuilder.Entity("BankApp.Models.BankCharges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DifferentBankIMPSCharge")
                        .HasColumnType("int");

                    b.Property<int>("DifferentBankRTGSCharge")
                        .HasColumnType("int");

                    b.Property<int>("SameBankIMPSCharge")
                        .HasColumnType("int");

                    b.Property<int>("SameBankRTGSCharge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BankCharges");
                });

            modelBuilder.Entity("BankApp.Models.BankModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BankChargesId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankChargesId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BankApp.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankModelId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("BankApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankModelId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BankApp.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountHolderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TxnId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountHolderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankApp.Models.AccountHolder", b =>
                {
                    b.HasOne("BankApp.Models.BankModel", null)
                        .WithMany("AccountHolders")
                        .HasForeignKey("BankModelId");
                });

            modelBuilder.Entity("BankApp.Models.BankModel", b =>
                {
                    b.HasOne("BankApp.Models.BankCharges", "BankCharges")
                        .WithMany()
                        .HasForeignKey("BankChargesId");

                    b.Navigation("BankCharges");
                });

            modelBuilder.Entity("BankApp.Models.Currency", b =>
                {
                    b.HasOne("BankApp.Models.BankModel", null)
                        .WithMany("Currencies")
                        .HasForeignKey("BankModelId");
                });

            modelBuilder.Entity("BankApp.Models.Employee", b =>
                {
                    b.HasOne("BankApp.Models.BankModel", null)
                        .WithMany("Employees")
                        .HasForeignKey("BankModelId");
                });

            modelBuilder.Entity("BankApp.Models.Transaction", b =>
                {
                    b.HasOne("BankApp.Models.AccountHolder", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountHolderId");
                });

            modelBuilder.Entity("BankApp.Models.AccountHolder", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankApp.Models.BankModel", b =>
                {
                    b.Navigation("AccountHolders");

                    b.Navigation("Currencies");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
